# Generated by Django 2.0.1 on 2018-07-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='cake_discount',
            field=models.CharField(default=10000, max_length=10, verbose_name='现价'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='cake_price',
            field=models.CharField(default=10000, max_length=10, verbose_name='原价'),
        ),
    ]
