# Generated by Django 2.0.1 on 2018-07-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='number',
            field=models.CharField(default=1, max_length=10, verbose_name='原价'),
        ),
    ]
